# Generated by Django 2.2.7 on 2020-07-23 15:18

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='RunDB',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('TASK', models.IntegerField()),
                ('CSV_FILE', models.FileField(upload_to='database')),
                ('DEP_VAR', models.IntegerField()),
            ],
            options={
                'db_table': 'run_db',
            },
        ),
    ]
